### ISSUE TITLE
Issue: Rendering Correct Authenticated User Data

### ISSUE THREAD

**Issue by Bsakwa** [tykoon787/lawris#15]
### Problem
Following codebase restructuring to handle both normal and Firebase logins, there's a discrepancy in rendering the correct authenticated user's name, especially after a normal login.

### Details
- After a normal login, the application fails to consistently display the accurate authenticated user's name.
- This inconsistency affects user experience by displaying incorrect user information.

### Proposed Solution
- Ensure uniform handling of user data post successful authentication, abstracting differences between authentication methods.
- Implement a standardized mechanism to retrieve user information, irrespective of the login method used.
- Update the application state/components accurately after a normal login to reflect the logged-in user's details.

### Next Steps
1. Test scenarios involving both normal and Firebase logins to validate the proposed solution.
2. Centralize user information rendering logic for consistency across the application.

### Additional Notes
- Resolving this issue is crucial for maintaining a consistent user experience after login, irrespective of the authentication method.

**Comment by Bsakwa** [comment]
Yes @Annetaliya Am working on it as we speak. I will let you know once I make progress. Impressed by the work you have done on the previous issue. Well done!

**Comment by Annetaliya** [comment]
Thank you I'm getting a hang of it will update you in a bit on my progress

**Comment by Annetaliya** [comment]
Hey I have fixed the problem you can close this now
