### ISSUE TITLE
Authenticated Session Lost on Page Reload

### ISSUE THREAD

**Issue by Bsakwa** [tykoon787/lawris#17]
### Description

Upon logging into the app and subsequently reloading the page, the authenticated session is lost, requiring users to log in again.

### Expected Behavior

The app's authenticated session should persist across page reloads, allowing users to stay logged in without needing to re-authenticate frequently.

### Steps to Reproduce

1. Log into the app.
2. Reload the page (or perform specific actions).
3. Observe that the authenticated session is lost.

### Possible Causes/Investigation Points

- **Session Expiry Configuration:** Check session duration settings to ensure it's not causing premature expiration.
- **Handling of Session Data:** Review how session data is managed and retrieved upon page reload.
- **Server-Side Configurations:** Investigate server-side code related to session management.
- **Storage Mechanism:** Examine how authentication tokens/session data are stored (cookies, local storage) and retrieved.
- **Network Errors:** Look for any errors in network requests/responses affecting session data.

### Possible Solutions/Ideas

1. **Session Expiry Check:** Ensure the session duration is appropriately set, preventing premature expiration.
2. **Session Persistence Handling:** Review how the app stores and retrieves session data upon reload.
3. **Server-Side Debugging:** Investigate server-side code related to session management for any discrepancies.
4. **Storage Mechanism Inspection:** Verify if the authentication tokens/session data storage (cookies/local storage) is consistent.
5. **Network Error Handling:** Check for any network errors affecting session data retrieval.

This issue significantly impacts user experience and needs urgent attention to maintain seamless authentication.

Your contributions or insights into resolving this issue would be highly appreciated.

**Comment by Annetaliya** [comment]
Hi, I have already sorted this issue.

**Comment by Bsakwa** [comment]
This has been noted. Thanks Annette. Notify me when to pull your changes.
